# Generated by Django 6.0.6 on 2026-07-05 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "industry",
                    models.CharField(
                        choices=[
                            ("manufacturing", "Manufacturing"),
                            ("construction", "Construction"),
                            ("mining", "Mining"),
                            ("office", "Office / General"),
                        ],
                        default="office",
                        max_length=50,
                    ),
                ),
                (
                    "subscription_tier",
                    models.CharField(
                        choices=[
                            ("core", "Core"),
                            ("attendance", "Attendance & Leave"),
                            ("hse", "HSE + Man Hours"),
                            ("payroll", "Full Suite"),
                        ],
                        default="core",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "geofence_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "geofence_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("geofence_radius_meters", models.IntegerField(default=100)),
                ("emp_number_prefix", models.CharField(default="NXS", max_length=10)),
            ],
            options={
                "db_table": "companies_company",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("has_attendance", models.BooleanField(default=False)),
                ("has_hse", models.BooleanField(default=False)),
                ("has_payroll", models.BooleanField(default=False)),
                (
                    "price_per_employee_per_month",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "companies_subscription_plan",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="CompanySubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("billing_period_start", models.DateField()),
                ("billing_period_end", models.DateField()),
                ("active_employee_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_subscription",
                        to="companies.company",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="companies.subscriptionplan",
                    ),
                ),
            ],
            options={
                "db_table": "companies_company_subscription",
                "ordering": ["-billing_period_end"],
            },
        ),
    ]
