# Generated by Django 6.0.6 on 2026-07-08 10:36

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0002_alter_companysubscription_company"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=20)),
                ("name", models.CharField(max_length=255)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="companies.company",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="departments.department",
                    ),
                ),
            ],
            options={
                "db_table": "departments_department",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("level", models.CharField(db_index=True, max_length=20)),
                (
                    "base_salary_min",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "base_salary_max",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="companies.company",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="positions",
                        to="departments.department",
                    ),
                ),
            ],
            options={
                "db_table": "departments_position",
                "ordering": ["department", "level", "title"],
            },
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["company", "is_active"], name="idx_dept_comp_active"
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["company", "parent"], name="idx_dept_comp_parent"
            ),
        ),
        migrations.AddConstraint(
            model_name="department",
            constraint=models.UniqueConstraint(
                fields=("company", "code"), name="uq_departments_company_code"
            ),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(
                fields=["company", "is_active"], name="idx_pos_comp_active"
            ),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(
                fields=["company", "department"], name="idx_pos_comp_dept"
            ),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(fields=["company", "level"], name="idx_pos_comp_level"),
        ),
        migrations.AddConstraint(
            model_name="position",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("base_salary_min__lte", models.F("base_salary_max"))
                ),
                name="ck_positions_salary_min_lte_max",
            ),
        ),
    ]
