# Generated by Django 6.0.6 on 2026-07-15 09:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeDocument",
            fields=[
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("ktp", "KTP"),
                            ("npwp", "NPWP"),
                            ("contract", "Contract"),
                            ("ijazah", "Ijazah"),
                            ("sim", "SIM"),
                            ("sertifikat", "Sertifikat"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("file_url", models.CharField(blank=True, default="", max_length=512)),
                ("file_name", models.CharField(blank=True, default="", max_length=255)),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "db_table": "documents_employee_document",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["employee", "doc_type"], name="idx_empdoc_employee_type"
                    ),
                    models.Index(
                        fields=["employee", "is_active"],
                        name="idx_empdoc_employee_active",
                    ),
                ],
            },
        ),
    ]
