# Generated by Django 6.0.6 on 2026-07-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("table_name", models.CharField(max_length=255)),
                ("record_id", models.BigIntegerField(db_index=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Created"),
                            ("UPDATE", "Updated"),
                            ("DELETE", "Deleted"),
                        ],
                        max_length=10,
                    ),
                ),
                ("user_id", models.BigIntegerField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("before_data", models.JSONField(blank=True, null=True)),
                ("after_data", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "audit_audit_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["table_name", "record_id"],
                        name="audit_audit_table_n_68da2d_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="audit_audit_created_837eb2_idx"
                    ),
                    models.Index(
                        fields=["user_id"], name="audit_audit_user_id_1df24f_idx"
                    ),
                ],
            },
        ),
    ]
